# Netlify configuration file
[build]
  command = "npm run build"
  publish = ".next"

# Environment variables needed for build
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  # Disable all forms of secrets scanning for Google Maps API keys
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  NETLIFY_SECRETS_SCAN_ENABLED = "false"

# Ensure Next.js is properly handled
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for proper caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect handling for images
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }
